pruebas_index:
    path: /pruebas/{name}/{page}
    defaults: { _controller: AppBundle:Pruebas:index, name:morales, page:1 }
    methods: [GET, POST]
    requirements:
        page: \d+
        
pruebas_create:
    path: /pruebas/create
    defaults: { _controller: AppBundle:Pruebas:create }
    methods: [GET, POST]
    
pruebas_read:
    path: /pruebas/read
    defaults: { _controller: AppBundle:Pruebas:read }